# 
# Do not Edit! Generated by:
# spectacle version 0.13
# 
# >> macros
# << macros

Name:       libexif
Summary:    Library for extracting extra information from image files
Version:    0.6.19
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://libexif.sourceforge.net/
Source0:    http://downloads.sourceforge.net/project/libexif/libexif/%{version}/libexif-%{version}.tar.bz2
Source1:    libexif-docs.tar.gz
Source100:  libexif.yaml
Requires(post):  /sbin/ldconfig
Requires(postun):  /sbin/ldconfig

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
Most digital cameras produce EXIF files, which are JPEG files with
extra tags that contain information about the image. The EXIF library
allows you to parse an EXIF file and read the data from those tags.



%package devel
Summary:    Files needed for libexif application development
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The libexif-devel package contains the libraries and header files
for writing programs that use libexif.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# to avoid multilib conflicts, we toss in pre-generated docs
# and neuter make all in the docs dir
tar xzf %{SOURCE1}
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-docs

# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -rf $RPM_BUILD_ROOT%{_datadir}/doc/libexif
cp -R doc/doxygen-output/libexif-api.html .
iconv -f latin1 -t utf-8 < COPYING > COPYING.utf8; cp COPYING.utf8 COPYING
iconv -f latin1 -t utf-8 < README > README.utf8; cp README.utf8 README
# << install post
%find_lang libexif-12

%clean
rm -rf %{buildroot}



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig



%files -f libexif-12.lang
%defattr(-,root,root,-)
# >> files
%doc COPYING README NEWS
%{_libdir}/libexif.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%doc libexif-api.html
%{_includedir}/libexif
%{_libdir}/*.so
%{_libdir}/pkgconfig/libexif.pc
# << files devel

